### ISSUE TITLE
Large images don't display preview in Backend

### ISSUE THREAD

**Issue by Leuloch** [rjchauhan/RJGallery-for-OctoberCMS#11]
On the backend, when I upload large images, the preview of the image don't display properly.
See the image below:
![rjgallery](https://cloud.githubusercontent.com/assets/5075742/7694117/1fd44d5a-fdb2-11e4-9c2b-9fc3cd83731e.jpg)
The preview of the images 1, 2, 5 and 6 are blank.
This behavior don't affect the gallery in front-end.

**Comment by vojtasvoboda** [comment]
I think this is problem with CMS core: [octobercms/october](https://github.com/octobercms/october) and it should be reported here, BUT:

Try to update to latest version. I tried 58MB (resolution 13248 × 6624) photo and worked well:

![snimek obrazovky 2015-09-14 v 12 02 33](https://cloud.githubusercontent.com/assets/374917/9847246/e7c94964-5ad7-11e5-8481-d36229cc20c5.png)

**Comment by rjchauhan** [comment]
It's solved with the latest version of OctoberCMS.
