### ISSUE TITLE
init vars in onRun instead of onRender

### ISSUE THREAD

**Issue by gregorybleiker** [rjchauhan/RJGallery-for-OctoberCMS#14]
Wouldn't it be better to run the code that is now in onRender in the gallery component in the onRun function instead? That way one could include the component without having to actually display it in order to access the "gallery" variable. The use case for this is a page that wants to get a list of the images without actually displaying the gallery.

**Comment by vojtasvoboda** [comment]
Inicialization variables in `onRun()` **doesn't work** with more then one gallery.

Two galleries with init in `onRender()`:

![snimek obrazovky 2015-09-14 v 11 52 36](https://cloud.githubusercontent.com/assets/374917/9847110/070c47e6-5ad7-11e5-96d4-8c666bfe5ae5.png)

Two galleries with init in `onRun()`:

![snimek obrazovky 2015-09-14 v 11 52 20](https://cloud.githubusercontent.com/assets/374917/9847121/1530b050-5ad7-11e5-93b0-9e3ffbd5447b.png)

Doesn't works - every gallery renders identical photo set.

**Comment by gregorybleiker** [comment]
Interesting, I don't see why this should be from the code... how do you
include the galleries on the page?

**Comment by vojtasvoboda** [comment]
Just created two separated galleries, created new page test.htm, choose default layout and insert two gallery components with default settings. Nothing else.

![snimek obrazovky 2015-09-14 v 22 28 36](https://cloud.githubusercontent.com/assets/374917/9860940/6dbdc66a-5b2f-11e5-972b-efd2b7f9a799.png)
