### ISSUE TITLE
Not working with latest October build

### ISSUE THREAD

**Issue by amdad** [rjchauhan/RJGallery-for-OctoberCMS#28]
Hello, thanks for plugin. But it need, some update to fit newest October builds.
![error](https://cloud.githubusercontent.com/assets/10062429/14999691/16f4334c-118b-11e6-9a77-91cd89cb2981.png)

**Comment by cracki** [comment]
in controller/gallery/config_form.yaml:
change to:
form: $/raviraj/rjgallery/models/gallery/fields.yaml
and 
in controller/gallery/config_list.yaml:
change to:
list: $/raviraj/rjgallery/models/gallery/columns.yaml

**Comment by rjchauhan** [comment]
fixed in latest version
