### ISSUE TITLE
LightGallery update ??

### ISSUE THREAD

**Issue by damsfx** [rjchauhan/RJGallery-for-OctoberCMS#36]
Hi,

Can we expect an update that will include the lastest LightGallery scripts ?
The current release verion is 1.4 : https://github.com/sachinchoolur/lightGallery

Another cool feature : 
Like there's a "jqueryinject" option, a new one to disable script's and css sheet's injection for sites that already have 'LightGallery' for light-boxing images.

```
            'globalinject' => [
                'title'             => 'raviraj.rjgallery::lang.globalinject.title',
                'description'       => 'raviraj.rjgallery::lang.globalinject.description',
                'type'              => 'dropdown',
                'default'           => 'yes',
                'options'           => ['yes'=>'...,'no'=>'...']
            ],
```
And some changes in components 
```
$this->addJs('assets/js/lightGallery.min.js');  
$this->addCss('assets/style/lightGallery.css');
```
in
```
if($this->property('globalinject')=="yes")
{
   $this->addJs('assets/js/lightGallery.min.js');
   $this->addCss('assets/style/lightGallery.css');
}
```

Thank's for your time !

**Comment by rjchauhan** [comment]
Upgraded!

**Comment by damsfx** [comment]
Hi,

LightGallery whas upgraded to version 1.4, that's nice.   

Just have a little question ...   
If the template already use the LighGallery scripts globaly (for the lightbox effect on some isolated images), it may cause crash having it loaded twice.

Have you planned to have a switch to Whether or not load the LightGallery scripts !?

If not, I would extend your plugin cause I need to have more precision on whitch scripts to inject, particularly for lightGallery plugins (share, hash ...).
