### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by gregoryloichot** [rjchauhan/RJGallery-for-OctoberCMS#37]
Hi, 

I'm using your plugin on a website, and it works well. But on iOS (Safari, Firefox and Chrome), when clicking on a image in a gallery, nothing happen and the message "A problem occurred with this web page, so it was reloaded".

With the iOS simulator (on a Mac), it works. It also works on Safari desktop.

You can check on https://goo.gl/pW48TE

Thanks.

**Comment by rjchauhan** [comment]
can you try upgrading plugin? I just deployed new version today. let me know if you get this issue again.

**Comment by gregoryloichot** [comment]
Hi, 

The upgrade look good.

But before, I could do : 

```
[gallerySlug]
slug = "{{ :slug }}"
lang = "Gallery"
jqueryinject = "no"
...
==
<div class="big-title">
    <div class="background green">
        <h1>
            {{ gallerySlug.gallery.title }}
        </h1>
    </div>
</div>
<div class="container gallery">
    <div class="row">
        <div class="col-xs-12">
            <p>{{ gallerySlug.gallery.description|raw }}</p>
            {% component 'gallerySlug' %}
        </div>
    </div>
</div>
```
to display gallery description and title. It no longer works. Any idea?

**Comment by gregoryloichot** [comment]
Sorry, `{{ gallery.name }}` is fine.
Thanks.
