### ISSUE TITLE
lightGallery.min.js

### ISSUE THREAD

**Issue by gregoryloichot** [rjchauhan/RJGallery-for-OctoberCMS#38]
Hi, 

On case sensitive OS, light**g**allery.min.js cannot be found, because the file is named light**G**allery.min.js. 

`mv lightGallery.min.js lightgallery.min.js` fixes the bug.

**Comment by rjchauhan** [comment]
file name is `lightgallery.min.js` and injected using the same name `$this->addJs('assets/js/lightgallery.min.js');`. Seems like you don't have all the files updated, please check and compare github code with your local code.

**Comment by rjchauhan** [comment]
pull code once again

**Comment by rjchauhan** [comment]
just deployed new version with this fix, update plugin!

**Comment by gregoryloichot** [comment]
Ok, thanks.
